create extension if not exists pgcrypto;

-- =========================
-- HELPERS
-- =========================

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$ language plpgsql;


-- =========================
-- AUTH / USERS
-- =========================

create table if not exists public.users (
  id text primary key,
  email text not null unique,
  "passwordHash" text not null,
  role text not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();


create table if not exists public.user_sessions (
  id text primary key,
  "userId" text not null,
  "tokenHash" text not null unique,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz not null default now(),

  constraint user_sessions_userId_fkey
    foreign key ("userId") references public.users(id)
    on delete cascade
);

create index if not exists user_sessions_userId_idx on public.user_sessions ("userId");
create index if not exists user_sessions_expiresAt_idx on public.user_sessions ("expiresAt");


-- =========================
-- CHANNELS / WHALES / ALERTS
-- =========================

create table if not exists public.channels (
  id text primary key,
  name text not null,
  slug text not null unique,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

drop trigger if exists channels_set_updated_at on public.channels;
create trigger channels_set_updated_at
before update on public.channels
for each row execute function public.set_updated_at();


create table if not exists public.whales (
  id text primary key,
  name text not null,
  "channelId" text,
  "createdAt" timestamptz not null default now(),

  constraint whales_channelId_fkey
    foreign key ("channelId") references public.channels(id)
    on update cascade
    on delete set null
);

create index if not exists whales_channelId_idx on public.whales ("channelId");


-- =========================
-- DEEPSIGNAL / MARKETS
-- =========================
-- Nota: esta tabla representa el mercado analizado.
-- No reemplaza alerts. Alerts sigue siendo "alerta de whale".

create table if not exists public.markets (
  id uuid primary key default gen_random_uuid(),

  "externalMarketId" text not null,
  platform text not null default 'polymarket',

  title text not null,
  description text,
  category text,
  url text,

  "closeDate" timestamptz,
  "currentProbability" double precision,
  "previousProbability24h" double precision,
  "probabilityChange24h" double precision,
  volume double precision,
  liquidity double precision,
  outcomes jsonb,

  "lastUpdated" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),

  constraint markets_platform_external_unique unique (platform, "externalMarketId")
);

create index if not exists markets_platform_idx on public.markets (platform);
create index if not exists markets_category_idx on public.markets (category);
create index if not exists markets_closeDate_idx on public.markets ("closeDate");
create index if not exists markets_currentProbability_idx on public.markets ("currentProbability");

drop trigger if exists markets_set_updated_at on public.markets;
create trigger markets_set_updated_at
before update on public.markets
for each row execute function public.set_updated_at();


create table if not exists public.alerts (
  id integer generated by default as identity primary key,

  "whaleId" text not null,
  "whaleName" text not null,
  action text not null,
  answer text not null,
  "marketTitle" text not null,

  "marketId" text,
  "deepMarketId" uuid,
  "polymarketUrl" text,
  "eventSlug" text,
  "telegramDate" timestamptz,

  resolved boolean not null default false,
  result text,
  "isWin" boolean,

  "sizeUsd" double precision not null,
  "priceCents" integer not null,
  shares integer not null,
  "rawText" text not null,
  hash text not null unique,
  "createdAt" timestamptz not null default now(),

  constraint alerts_whaleId_fkey
    foreign key ("whaleId") references public.whales(id)
    on update cascade
    on delete restrict,

  constraint alerts_deepMarketId_fkey
    foreign key ("deepMarketId") references public.markets(id)
    on update cascade
    on delete set null
);

create index if not exists alerts_whaleId_idx on public.alerts ("whaleId");
create index if not exists alerts_marketId_idx on public.alerts ("marketId");
create index if not exists alerts_deepMarketId_idx on public.alerts ("deepMarketId");
create index if not exists alerts_eventSlug_idx on public.alerts ("eventSlug");
create index if not exists alerts_createdAt_idx on public.alerts ("createdAt");


create table if not exists public.user_channels (
  id text primary key,
  "userId" text not null,
  "channelId" text not null,
  unlocked boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),

  constraint user_channels_userId_fkey
    foreign key ("userId") references public.users(id)
    on delete cascade,

  constraint user_channels_channelId_fkey
    foreign key ("channelId") references public.channels(id)
    on delete cascade,

  constraint user_channels_user_channel_unique unique ("userId", "channelId")
);

create index if not exists user_channels_userId_idx on public.user_channels ("userId");
create index if not exists user_channels_channelId_idx on public.user_channels ("channelId");

drop trigger if exists user_channels_set_updated_at on public.user_channels;
create trigger user_channels_set_updated_at
before update on public.user_channels
for each row execute function public.set_updated_at();


-- =========================
-- SYSTEME / PAYMENTS
-- =========================

create table if not exists public.customer_access (
  id text primary key,
  email text not null unique,
  status text not null default 'active',
  provider text not null default 'systeme',

  "systemeCustomerId" text,
  "systemeContactId" text,
  "systemeOrderId" text,
  "systemeOrderItemId" text,
  "systemePricePlanId" text,
  "productName" text,

  "userId" text unique,
  "activatedAt" timestamptz,
  "cancelledAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),

  constraint customer_access_userId_fkey
    foreign key ("userId") references public.users(id)
    on delete set null
);

create index if not exists customer_access_status_idx on public.customer_access (status);

drop trigger if exists customer_access_set_updated_at on public.customer_access;
create trigger customer_access_set_updated_at
before update on public.customer_access
for each row execute function public.set_updated_at();


create table if not exists public.invite_tokens (
  id text primary key,
  "accessId" text not null,
  email text not null,
  "tokenHash" text not null unique,
  "expiresAt" timestamptz not null,
  "usedAt" timestamptz,
  "createdAt" timestamptz not null default now(),

  constraint invite_tokens_accessId_fkey
    foreign key ("accessId") references public.customer_access(id)
    on delete cascade
);

create index if not exists invite_tokens_email_idx on public.invite_tokens (email);
create index if not exists invite_tokens_expiresAt_idx on public.invite_tokens ("expiresAt");


create table if not exists public.payment_events (
  id text primary key,
  provider text not null default 'systeme',
  "eventType" text not null,
  "messageId" text unique,
  "deliveryId" text,
  "payloadHash" text not null unique,
  email text,
  "rawPayload" jsonb not null,
  "receivedAt" timestamptz not null default now()
);

create index if not exists payment_events_email_idx on public.payment_events (email);
create index if not exists payment_events_eventType_idx on public.payment_events ("eventType");


-- =========================
-- DEEPSIGNAL CONTEXT
-- =========================

create table if not exists public.market_context (
  id uuid primary key default gen_random_uuid(),
  "marketId" uuid not null,

  "sourceTitle" text not null,
  "sourceUrl" text,
  "publishedDate" timestamptz,
  summary text not null,
  "relevanceScore" double precision,

  "createdAt" timestamptz not null default now(),

  constraint market_context_marketId_fkey
    foreign key ("marketId") references public.markets(id)
    on delete cascade
);

create index if not exists market_context_marketId_idx on public.market_context ("marketId");
create index if not exists market_context_publishedDate_idx on public.market_context ("publishedDate");


create table if not exists public.pipeline_runs (
  id uuid primary key default gen_random_uuid(),

  "startedAt" timestamptz not null default now(),
  "finishedAt" timestamptz,
  "marketsFetched" integer,
  "marketsFiltered" integer,
  "marketsAnalyzed" integer,
  status text not null,
  "errorMessage" text,

  "createdAt" timestamptz not null default now()
);

create index if not exists pipeline_runs_status_idx on public.pipeline_runs (status);
create index if not exists pipeline_runs_startedAt_idx on public.pipeline_runs ("startedAt");


create table if not exists public.deepbriefs (
  id uuid primary key default gen_random_uuid(),

  "marketId" uuid not null,
  "pipelineRunId" uuid,

  "lecturaClave" text,
  "radarScore" double precision not null,
  "radarScoreBreakdown" jsonb,
  "signalLabel" text,

  "estelaDeCapital" text,
  "entornoDeSenal" jsonb,
  "corrienteNarrativa" text,
  "filtroDeRuido" jsonb,
  premortem jsonb,
  "mapaDeRuptura" jsonb,
  "mapaDeEscenarios" jsonb,
  "actualizacionBayesiana" jsonb,

  "deepsignalVerdict" text,
  "confidenceLevel" text,
  "watchTriggers" jsonb,

  "rawOutput" jsonb,
  "createdAt" timestamptz not null default now(),

  constraint deepbriefs_marketId_fkey
    foreign key ("marketId") references public.markets(id)
    on delete cascade,

  constraint deepbriefs_pipelineRunId_fkey
    foreign key ("pipelineRunId") references public.pipeline_runs(id)
    on delete set null
);

create index if not exists deepbriefs_marketId_idx on public.deepbriefs ("marketId");
create index if not exists deepbriefs_pipelineRunId_idx on public.deepbriefs ("pipelineRunId");
create index if not exists deepbriefs_radarScore_idx on public.deepbriefs ("radarScore");
create index if not exists deepbriefs_signalLabel_idx on public.deepbriefs ("signalLabel");
create index if not exists deepbriefs_createdAt_idx on public.deepbriefs ("createdAt");


-- =========================
-- GRANTS PARA PRISMA
-- =========================

grant usage on schema public to prisma;
grant create on schema public to prisma;
grant all on all tables in schema public to prisma;
grant all on all routines in schema public to prisma;
grant all on all sequences in schema public to prisma;

alter default privileges for role postgres in schema public grant all on tables to prisma;
alter default privileges for role postgres in schema public grant all on routines to prisma;
alter default privileges for role postgres in schema public grant all on sequences to prisma;